### PR TITLE
Add Sponsor Us page

### PR DESCRIPTION
**Pull request by ifosch**
This renders the Sponsor Us page to be written in FM using MD or
HTML. This includes a reusable template.

We have a few pages which should show different groups of options with
different sets of attributes each, one of them is the Sponsor Us page,
under Association/Collaborate.

This PR propose two different implementation approaches, you can find
in separate commits:
* **All content in plain HTML**: This was my first approach, making
the whole content to be written in the MD file for the page in plain
HTML, since Markdown doesn't support `dl`s.
* **Templated with content in MD/HTML front-matter**: One first
iteration was to put the content in MD or HTML in FM, and have a
template rendering this. Besides it makes editing easier, it also
generalizes this kind of pages, i.e. groups of options with different
sets of attributes each.

Both approaches show basically the same content, with the only
difference is the last one uses `ul`s a little bit more, but I think
it's still visually and conceptually nice.

The questions have been made collapsable for easier reading.

## Desktop rendered

desktop-1
desktop-2
desktop-3

## Mobile rendered

mobile-1
mobile-2

### CODE REVIEW

**Comment by ifosch** [comment]
I figured out another approach, using separate pages for each group,
but I found this would be creating a lot more files, and, at least,
one more subdirectory in the tree, without providing too much easiness
or improvement.

I kept two separate commits just to make easy to see how each approach
is, but I would merge both if the last approach is chosen. Also, I'm
open to iterate a little bit more, but I don't think this is worth
until we found another use case we want to improve with this.

**Comment by rberenguel** [comment]
I'm not sure about the markdown one. I like it in principle, but the frontmatter gets very long and noisy. Of course, the HTML version is also long and noisy, but it's theoretically easier to edit. I assume though that in the end this page is going to be "mostly static" right? So, we won't be adding many more blocks or information aside from maybe editing something already there? If that is the case, I would prefer the markdown version. I think visually it looks nice, although I would consider merging the columns for the headers (what do you get, etc). I guess this requires a next iteration on the approach, since it seems impossible with the current implementation. A way around this would be having named sections in the frontmatter (` `whatdoyouget`) and then iterating throough those, then the common title can be handled as part of each section, but that would make other parts more verbose.

**Comment by ifosch** [comment]
I uncertain if you like the final version in the proposal.
Some of these pages are being created now because of recent activities being proposed and received, so I think we might have more edition as the Association activities and proposal reception increase.
Also, we'll have more pages with a similar structure but different names for the sections, like the _Organize with us_ or _Promote your event_ pages, as seen in the texts proposal discussed in GDrive. I went into the second iteration to provide an easy and flexible way to create more similar pages.
About front matter's length and noise, this is the only improvement I see in iterating to a multiple files setup, similar to the people pages. I thought about this option, and counted having one more directory, with five more files, and still a front matter pretty long, what seems very little improvement.
About the visual merge of the columns... I would use CSS to modify the visualization of the terms and descriptions in the DL, without changing the structure.
I think HTML is harder to edit and read than Markdown, also error prone. I would use Markdown in the content instead of front matter, but Markdown cannot represent description lists, so HTML is the only way to represent them.
The different section names among these new pages cause the need to explicit the section name, instead of going right to what we need in this specific page making the template too specific to reuse.

**Comment by ifosch** [comment]
@rberenguel :point_up:

**Comment by rberenguel** [comment]
We can't merge columns with just CSS. The way the page is right now begs for having a common "Conditions", centered, for the three columns appearing now. With a td this would be a colspan="0", but as the template is right now each column is fully independent, where this page doesn't _really_ have independent columns, all have a common set of attributes (the section headers).

As I said, I'm not super-convinced of such long front matters. YAML is not the easiest language to edit and when for some reason it fails, it's hard to debug. But I agree that with HTML it is not much easier, so I guess this is the lesser evil. Note that my comments above are about the hugo template in the end, and not about what goes into the frontmatter (although it may need to be modified to suit the template).

We could pivot how the frontmatter/blocks are constructed, so we have blocks per section. Something like this, I mean:

```
header: "Regular monthly events" 
blocks:
    - content: PyBCN meetups # This could be a subheader block or whatever is semantically clear
    - content: PyLadies BCN
    ...
subheader: What do you get # A centered text common for all the blocks
blocks:
   - content: what do you get, column 1 (pybcn)
   - content: what do you get, column 2 (pyladies)
   ...
```

Or something around these lines: visually having three times "what do you get", "conditions", "nice to haves" without any alignment is not great. I think pivoting the way this is built. There may be other ways to achieve this approach, I think for this page it would make a difference. Not sure about others, though.

**Comment by ifosch** [comment]
@rberenguel I don't like changing the YAML structure because looks more error prone to editors. I tried using other kind or arrangement of DOM objects but these made responsiveness harder or impossible. Also, @lpmayos suggestion about using collapsable questions looked much more interesting, so I went for this.
I added the correct class to have responsive blocks. I also added the collapsing questions. I found that trying to make the sections collapsable caused the blocks to render vertically even on wide enough screens and the size of the whole size is still short enough, so I left the second level of collapsable objects off for now. I hope these changes are enough.
The PR contains separated commits so you can review these separately, in case there are more changes to be done. I would also add documentation on how to use this template for further editing, so please, confirm if you like it like this or you see any other change to be done, but don't merge this PR yet.

**Comment by ifosch** [comment]
I've solved requests about the style applied to the lists. I also added the documentation. I couldn't find any good solution to the problem of the misaligned boxes, I hope with the collpased styles this would be a little bit mitigated. I also couldn't find any other good approach to organize the items. Let me know any issue you may find @rberenguel @lpmayos

**Pull request merged**
