### PR TITLE
Add membership page

### PR DESCRIPTION
**Pull request by rberenguel**

### CODE REVIEW

**Comment by ifosch** [comment]
About the link in the collaborate page, now I'm realizing that might be better to move `content/pybcn_association/collaborate.md` to `content/pybcn_association/collaborate/_index.md`, making it use a new template which would show links to any other MD file in this directory, like `content/pybcn_association/collaborate/membership.md`. Maybe that makes more sense, so when designing the collaborate page, it would be easier. I would wait for this to be included in this change, so the page I'm working now is a sibling of the membership. What do you think @rberenguel ?

**Comment by rberenguel** [comment]
@ifosch 

- I'll remove the nesting
- I never merge already pushed commits on the command line (I don't even remember how it's done anymore). We have been using squash and merge on merging PRs:

image

I think this is easier as a practice (at work only admins can _not_ use squash and merge, it's the default per repository) since it doesn't require tinkering with git locally, that's simpler for everybody.

- Re: adding screenshots, yup, sorry, forgot :(
- Re: margin (or you mean border?), without it the page looks pretty cramped:

Now:
image

No margin nor border:

image

Margin and no border, looks too "airy":

image

About the `collaborate` part, if I understand it, yes, it makes sense. Would that bring a drop down to the main menu, so we would have collaborate > become a member? I think we need to have `become a member` be prominent in any case, so I hope that's the case (I think it will depend on the theme)

Do you want me to create this collaborate/_index.md template in this PR?

**Comment by ifosch** [comment]
- I'm not used to use the squash and merge, but we can start trying this. However, I think I would keep the form tags nesting, if you were referring to this, on your remove nesting comment.
- No worries about the screenshots, it was just a suggestion.
- Also, you are right, I meant the border. I see it is too airy, maybe making it some light gray, or maybe dark grey, but not black?
- About the files organization, I think it's ok by creating a pretty simple `content/collaborate/_index.md` with just a link to the `content/collaborate/membership.md`. Further work on the collaborate page's template can be left for later.
- Dropdown menus are a controversial discussion about design. When the page was designed, all the ways of collaborating were considered to be hosted in the Collaborate page, also to reduce the number of levels in the menu. However, this is the second time someone proposed to have more visibility for a collaborate second level page, like the Job Offers, so maybe we can rethink this. @lpmayos Your thoughts on this?

**Comment by lpmayos** [comment]
About the menu levels issue, I do not like having "ghost pages" that are not in the menu, but only accessible through other pages. It makes navigation clumsy from the UX point of view, making it difficult to find and sharing things. 

I'm not a UX expert, but I do not see anything bad with having three menu levels, as we have right now for the "events" section. We are building a corporate site with lots of information, and it would be very difficult that all fits in only two levels. 

Nevertheless, having a third level implies that there will not be a general "how to collaborate" page (or at least not directly accessible through the menu). What are your thoughts on this?

**Pull request merged**
